openapi: 3.0.3
info:
  title: "Normal title"
  version: "1.0.0"
  description: "**Markdown** with HTML: <img src=x onerror=alert('DESC')>"
tags:
  - name: test
    description: "<svg onload=alert('TAG')></svg>"
paths:
  /test:
    get:
      summary: "Test endpoint"
      description: "<div onclick=alert('PATH')>click</div>"
      responses:
        "200":
          description: "<script>console.log('RESPONSE')</script>"
