openapi: 3.0.3
info:
  title: "Normal title"
  version: "1.0.0"
  description: |
    <svg xmlns="http://www.w3.org/2000/svg" onload="alert('XSS2')"></svg>
tags:
  - name: test
    description: |
      <img src="x"
     style="position:fixed;top:0;left:0;width:100vw;height:100vh;opacity:0.01;z-index:99999"
     onclick="alert('CLICKED!')" />
paths:
  /test:
    get:
      summary: "Test endpoint"
      description: |
        <div onclick="alert('PATH')">click</div>
      responses:
        "200":
          description: |
            <script>alert('RESPONSE')</script>
