openapi: 3.0.3
info:
  title: Swagger iframe Injection Test
  version: "1.0.1"
  description: |
    <iframe src="https://evil.com"></iframe>
tags:
  - name: iframe-injection
    description: |
      <iframe src="https://evil.com"></iframe>
paths:
  /iframe:
    get:
      summary: "Test iframe injection endpoint"
      description: |
        <iframe src="https://evil.com"></iframe>
      responses:
        "200":
          description: |
            <iframe src="https://evil.com"></iframe>